### ISSUE TITLE
library '-lpthread ' not found

### ISSUE THREAD

**Issue by u04617** [qboticslabs/mastering_ros#20]
Hi Again,

I am getting this problem. When I try to compile this chapter. 

`CMake Error at /home/khan/catkin_ws/devel/share/gazebo_plugins/cmake/gazebo_pluginsConfig.cmake:141 (message):
  Project 'seven_dof_arm_gazebo' tried to find library '-lpthread'.`

Your kind suggestions would be highly appreciated and save lots of time. Thanks.

**Comment by qboticslabs** [comment]
Hi @u04617  Can you share the screenshots of the error? You can send to mail id: qboticslabs@gmail.com

**Comment by u04617** [comment]
Thank you very much. I am sorry for the late response. 
I have spent time on it again and I installed all possible packages for this chapter and now when I launch  

`roslaunch seven_dof_arm_bringup_moveit.launch `

I get following error

`Use the following script to fix incorrect usage:`
```
 find . -iname "*.xacro" | xargs sed -i 's#<\([/]\?\)\(if\|unless\|include\|arg\|property\|macro\|insert_block\)#<\1xacro:\2#g
when processing file: /home/khan/catkin_ws/src/chapter_3_codes/mastering_ros_robot_description_pkg/urdf/seven_dof_arm.xacro

xacro.py is deprecated; please use xacro instead
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/roslaunch/__init__.py", line 307, in main
    p.start()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/roslaunch/parent.py", line 268, in start
    self._start_infrastructure()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/roslaunch/parent.py", line 217, in _start_infrastructure
    self._load_config()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/roslaunch/parent.py", line 132, in _load_config
    roslaunch_strs=self.roslaunch_strs, verbose=self.verbose)
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/roslaunch/config.py", line 451, in load_config_default
    loader.load(f, config, verbose=verbose)
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/roslaunch/xmlloader.py", line 746, in load
    self._load_launch(launch, ros_config, is_core=core, filename=filename, argv=argv, verbose=verbose)
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/roslaunch/xmlloader.py", line 718, in _load_launch
    self._recurse_load(ros_config, launch.childNodes, self.root_context, None, is_core, verbose)
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/roslaunch/xmlloader.py", line 682, in _recurse_load
    val = self._include_tag(tag, context, ros_config, default_machine, is_core, verbose)
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/roslaunch/xmlloader.py", line 95, in call
    return f(*args, **kwds)
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/roslaunch/xmlloader.py", line 587, in _include_tag
    inc_filename = self.resolve_args(tag.attributes['file'].value, context)
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/roslaunch/xmlloader.py", line 183, in resolve_args
    return substitution_args.resolve_args(args, context=context.resolve_dict, resolve_anon=self.resolve_anon)
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/roslaunch/substitution_args.py", line 370, in resolve_args
    resolved = _resolve_args(resolved, context, resolve_anon, commands)
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/roslaunch/substitution_args.py", line 383, in _resolve_args
    resolved = commands[command](resolved, a, args, context)
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/roslaunch/substitution_args.py", line 151, in _find
    source_path_to_packages=source_path_to_packages)
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/roslaunch/substitution_args.py", line 197, in _find_executable
    full_path = _get_executable_path(rp.get_path(args[0]), path)
  File "/usr/lib/python2.7/dist-packages/rospkg/rospack.py", line 203, in get_path
    raise ResourceNotFound(name, ros_paths=self._ros_paths)
ResourceNotFound: seven_dof_arm_config
ROS path [0]=/opt/ros/kinetic/share/ros
ROS path [1]=/home/khan/catkin_ws/src
ROS path [2]=/opt/ros/kinetic/share`
```

I shall appreciate your kind response to resolve this issue. 

I have also sent you an email. Please help me resolve this. Thank you so much.

**Comment by qboticslabs** [comment]
Hi @u04617 

Sorry for the trouble, it may be because of the transition from Indigo to Kinetic. I can check the issue tomorrow and get back to you. I didn't get your mail.

Mail id: qboticslabs@gmail.com

**Comment by qboticslabs** [comment]
If you have problem with xacro, you can comment the following line in 

**mastering_ros_robot_description_pkg/urdf/seven_dof_arm.xacro**

like

**Comment by u04617** [comment]
Dear qboticslabs, 

Thank you for your kind response. I have tried after commenting those lines. It did not change anything. I still got the same response. Exactly similar to what I got in my last post. 

I am very thankful to you for taking time from your busy routine and helping me out. 

God Bless You.

**Comment by rk0dama** [comment]
you should do the command below to modify .xacro files in the directories: "urdf" and "urdf/sensors".
```
find . -iname "*.xacro" | xargs sed -i 's#<\([/]\?\)\(if\|unless\|include\|arg\|property\|macro\|insert_block\)#<\1xacro:\2#g'
```
and then, remove or comment out the following lines: Line 567-569
```
<xacro:base name="base"/>
<xacro:arm parent="base"/>
<xacro:gripper parent="tool"/>
```

after that, i could launch "view_arm.launch" in Kinetic.

**Comment by u04617** [comment]
@rk0dama rk0dama,

Thank You for your kind response. There is no problem in launching `view_arm_launch`. The problem is with `roslaunch seven_dof_arm_bringup_moveit.launch`. I am still facing the same problem. Your kind input will be highly valuable. Thanks. 

@qboticslabs 

I have sent you an email. Sorry for sending you so late. I shall wait for your kind response. 

Thank You 

Regards,
Dr. A. Mannan

**Comment by qboticslabs** [comment]
HI @u04617 

Can you make a new moveit config package? The existing package is created before 1 year, it will be good if you can create a new package using setup assistance. The procedure is also mentioned in the mail
