### ISSUE TITLE
Chapter 10 Pick and place action in Gazebo and real Robot is not working

### ISSUE THREAD

**Issue by sweetsaikiran690** [qboticslabs/mastering_ros#25]
[ INFO] [1503578128.869441377, 159.493000000]: Loading robot model 'seven_dof_arm'...
[ INFO] [1503578128.869527831, 159.493000000]: No root/virtual joint specified in SRDF. Assuming fixed joint
[ INFO] [1503578129.175303152, 159.707000000]: Loading robot model 'seven_dof_arm'...
[ INFO] [1503578129.175358182, 159.707000000]: No root/virtual joint specified in SRDF. Assuming fixed joint
[ WARN] [1503578129.182875417, 159.716000000]: The root link base_link has an inertia specified in the URDF, but KDL does not support a root link with an inertia.  As a workaround, you can add an extra dummy link to your URDF.
[ INFO] [1503578132.037467166, 162.185000000]: TrajectoryExecution will use old service capability.
[ INFO] [1503578132.037544704, 162.185000000]: Ready to take MoveGroup commands for group arm.
[ INFO] [1503578132.154141457, 162.284000000]: TrajectoryExecution will use old service capability.
[ INFO] [1503578132.154268683, 162.284000000]: Ready to take MoveGroup commands for group gripper.
[ERROR] [WallTime: 1503578133.005558] [162.997000] Grasp goal failed!: This goal was canceled because another goal was recieved by the simple action server
Traceback (most recent call last):
  File "/home/root1/Documents/ROS/Workspaces/Practise/src/mastering_ros/seven_dof_arm_gazebo/scripts/pick_and_place.py", line 393, in <module>
    main()
  File "/home/root1/Documents/ROS/Workspaces/Practise/src/mastering_ros/seven_dof_arm_gazebo/scripts/pick_and_place.py", line 385, in main
    p = Pick_Place()
  File "/home/root1/Documents/ROS/Workspaces/Practise/src/mastering_ros/seven_dof_arm_gazebo/scripts/pick_and_place.py", line 101, in __init__
    while not self._pickup(self._arm_group, self._grasp_object_name, self._grasp_object_width):
  File "/home/root1/Documents/ROS/Workspaces/Practise/src/mastering_ros/seven_dof_arm_gazebo/scripts/pick_and_place.py", line 306, in _pickup
    goal = self._create_pickup_goal(group, target, grasps)
  File "/home/root1/Documents/ROS/Workspaces/Practise/src/mastering_ros/seven_dof_arm_gazebo/scripts/pick_and_place.py", line 256, in _create_pickup_goal
    goal.possible_grasps.extend(grasps)
TypeError: 'NoneType' object is not iterable
terminate called after throwing an instance of 'boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<boost::lock_error> >'
  what():  boost: mutex lock failed in pthread_mutex_lock: Invalid argument
Aborted (core dumped)

**Comment by sweetsaikiran690** [comment]
roslaunch seven_dof_arm_gazebo seven_dof_arm_bringup_grasping.launch  -> Working fine
roslaunch seven_dof_arm_config moveit_planning_execution.launch     ->   Working fine
roslaunch seven_dof_arm_gazebo grasp_generator_server.launch       ->    Working fine

but
rosrun seven_dof_arm_gazebo pick_and_place.py        -> Not working
When run pick_and_place.py program, it is showing the logs or errors like above.


Please provide me the solution.

**Comment by ThadeuVBrito** [comment]
I had the same problem!

In my case, the solution was navigate via terminal into directory of **pick_and_place.py** and running the code:
`chmod 744 pick_and_place.py`
I hope it helps.
